### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by mazeyu** [dwalton76/rubiks-cube-NxNxN-solver#61]
The solver is amazing. I wrote a similar solver (not as powerful as yours) in April. I thought I was the first one, hhhh. I didn't use lookup tables, so it will be about ten minutes for 7x7x7. I noticed your solver is a little different than human?
I just feel excited to find someone doing things similar.
Best wishes,

Ma Zeyu

**Comment by dwalton76** [comment]
Thanks :)  There is a forum http://cubesolvingprograms.freeforums.net/ with some other folks that have written solvers for 4x4x4 and larger, you should check it out.

It is a bit out of date but I have a blog post from 2 years ago that describes the basics of how the solver works
http://programmablebrick.blogspot.com/2017/07/rubiks-cube-solver.html

I good bit has changed with it since then (back then it did not support NxNxN) but the core concepts are still the same.

**Comment by mazeyu** [comment]
Great! Thank you.

**Comment by mazeyu** [comment]
Plus, I also wrote a Megaminx Solver (but very slow, can be about twenty minutes). Do you know any guys doing that?
Thank you.
I think I will post a video of my solver on Youtube soon.

**Comment by dwalton76** [comment]
David Gilday did some robots for megaminx a few years ago:
- https://www.youtube.com/watch?v=P-S30fS944M
- https://www.youtube.com/watch?v=Ji7rF7KdmqE

He is the only person I know that has done a solver for megaminx

**Comment by mazeyu** [comment]
Thank you very much. I have made a video of my solver:
https://www.youtube.com/watch?v=2DRxdXR-t5o
=)
